apiVersion: v2
name: mcp-operator
description: A Helm chart for the mcp-operator
type: application
version: v0.35.1
appVersion: v0.35.1
home: https://github.com/openmcp-project/mcp-operator
sources:
  - https://github.com/openmcp-project/mcp-operator